uint8 map_mode
uint8 scan_mode
uint8 MODE_FROM_TOPIC = 0
uint8 MODE_FROM_SRV = 1
string map_path
string map_name
sensor_msgs/LaserScan scan
int32 max_num_of_candidates
---
string result
int32 num_of_candidates
geometry_msgs/TransformStamped[] candidates_tf_map_to_base
geometry_msgs/PoseWithCovarianceStamped[] candidates_robot_pose_on_map
float32[] scores